spring.application.name=Habit Tracker

# Configure the JDBC URL for the in-memory database
#spring.datasource.url=jdbc:h2:mem:habit_tracker
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.h2.console.enabled=true

# Configure the JDBC URL for the Mysql db
spring.datasource.url=jdbc:mysql://localhost:3306/habit_tracker
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update